### PR TITLE
Blog #3 Sarah Leichty

### PR DESCRIPTION
**Pull request by sleichty**

### CODE REVIEW

**Comment by andeek** [comment]
@sleichty Your image is .jpe not .jpg, which will not show up when compiling your document. Please correct and (re)commit (and push).

Thanks,
Andee

**Comment by sleichty** [comment]
I added the gif and pushed it. Is it better now?

**Comment by andeek** [comment]
Very close! You now have two extra files. Delete them and commit and push and it should be good to go. Check the "files changed" tab above to see which files I mean.

**Comment by sleichty** [comment]
Better? I deleted the two unwanted images.

**Comment by andeek** [comment]
Perfect, thanks!

**Pull request merged**
