### PR TITLE
my blog 2

### PR DESCRIPTION
**Pull request by rmartinezferia**

### CODE REVIEW

**Comment by andeek** [comment]
@rmartinezferia , I don't think you have synced your fork with the upstream before creating this PR. If you notice, you are changing files other than your own with this commit. Please sync your fork and recommit.

**Comment by rmartinezferia** [comment]
@andeek. I pulled again from upstreamed, resolved conflicts (using 'theirs') and pushed back to my origin. Will it work now?

**Comment by andeek** [comment]
If you look at the "files changed" tab, you are still changing files that aren't yours. Let's look at it together either before or after class.

**Comment by andeek** [comment]
@rmartinezferia Don't forget to open a new PR. Thanks!

**Pull request closed without merging**
