### PR TITLE
Ummm

### PR DESCRIPTION
**Pull request by jflater**
This seems extra messy?

### CODE REVIEW

**Comment by andeek** [comment]
@jflater  When was the last time you pulled from upstream? This seems messy to me too.

**Comment by jflater** [comment]
Last week I imagine, though I pulled from upstream in the directory today.

**Comment by jflater** [comment]
lab directory that is

**Comment by andeek** [comment]
This is pretty confusing, I'm gonna wait to merge until next week and we can look at it together.

**Comment by andeek** [comment]
Thanks!

**Pull request merged**
