### PR TITLE
deleted html file

### PR DESCRIPTION
**Pull request by ElkeBrandes**

### CODE REVIEW

**Comment by ElkeBrandes** [comment]
second try...

**Comment by Ranae** [comment]
Elke, we deleted the previous html file. Try making a pull request with the .Rmd file.

**Comment by ElkeBrandes** [comment]
Ok, I am confused. Let me try later tonight or tomorrow...

**Comment by andeek** [comment]
@ElkeBrandes, @Ranae  This should be resolved, no further action needed.

**Pull request merged**
